version: '3.2'

services:
  db:
    image: 'postgres:13.3'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db-folder:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres_db
  app:
    image: 'hello-world:10.0'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres_db
    links:
      - db